root_folder: machine-learning-8461284

mongodb:
  is_cloud: 0
  user_name: ashutosh
  password: 12345
  url: mongodb+srv://{0}:{1}@cluster0.wou64.mongodb.net/myFirstDatabase?retryWrites=true&w=majority


cloud_storage:
  azure_blob_storage:
    connection_str: DefaultEndpointsProtocol=https;AccountName=mlcloud12;AccountKey=1j7FZB6uU/DHDtajQ0tjMqD38y75n7qfgz22+OtC1+dwamAgGTlBQFf52pquWhT4XWll+Wla+vhtgMlDFtnYfA==;EndpointSuffix=core.windows.net
  aws_s3_bucket:
    name: aws_access_key
    Access Key ID: AKIAYPBYA4PJ3UXYYPRC
    Secret Access Key: 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
    description: AWS credentials

  gcp: gcp.json

watcher_checkpoint_storage_account_connection_str:
  connection_str: DefaultEndpointsProtocol=https;AccountName=storageaccountrgai1a757;AccountKey=j4TYtRYwIDyUNL4lKXXIfYgCftrTbJPhPHC8i/j66XSf6s81ruCaQqDnjh5WDMjrqqc4hulvZ8wxcYQb8KfukA==;EndpointSuffix=core.windows.net

azure_input_file_storage_connection_str:
  connection_str: DefaultEndpointsProtocol=https;AccountName=inputfilestorage;AccountKey=u2jUt3DLgsPiZO8S7kZ1yk4B7FJ6gCtdTeckaige1AXTnyPA1zby1w0n6HUi/2cdOAoo5E1jXrEeofyI6UDtFw==;EndpointSuffix=core.windows.net

event_hub_name_space:
  connection_str: Endpoint=sb://avnish327030.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=BwK0zozJe+Oz46F5BgpHUtq5zkzqMKCzPdc2kOg2WW8=


session:
  secret-key: ec6935d1-0e2c-4998-b7ed-809e8cb0fcda

user_detail:
  email_id: ashu@gmail.com
  role_id: 1 # 1 for admin and 2 for viewer

email_config:
  sender_email_id: kapil.shrm1.kks@gmail.com
  passkey: kpsyqtmygslgwgkc
  receiver_email_id:
    - rahulvarma1407@gmail.com
    - kapil.shrm1@gmail.com